VAR := \
    hello

all: foo bar
	do_something_with foo bar                                                   baz

foo:
		create_foo                                                              and not bar

bar:
	create_bar                                                                  and not foo
